from setuptools import setup, find_packages

setup(
    name="Wonkalytics",
    version="0.1.0",
    description="Analytics and logging tool for streaming interactions with OpenAI's API, with support for Azure SQL database logging.",
    author="Wonka",  
    author_email="s.vanderbijl@meetwonka.com",  
    url="https://github.com/MeetWonka/Wonkalytics",
    packages=find_packages(),
    install_requires=[
        "aiohttp==3.9.1",
        "aiosignal==1.3.1",
        "annotated-types==0.6.0",
        "anyio>=3.4.0",
        "async-timeout",
        "attrs",
        "certifi",
        "charset-normalizer",
        "click",
        "distro",
        "exceptiongroup",
        "fastapi",
        "frozenlist",
        "h11",
        "httpcore",
        "httpx",
        "idna",
        "iniconfig",
        "multidict",
        "openai",
        "packaging",
        "pluggy",
        "pydantic",
        "pydantic_core",
        "pyodbc",
        "pytest",
        "pytest-asyncio",
        "python-dotenv",
        "requests",
        "sniffio",
        "sse-starlette",
        "starlette",
        "tomli",
        "tqdm",
        "typing_extensions",
        "urllib3",
        "uvicorn",
        "yarl",
    ],
    classifiers=[
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.9",
        "Operating System :: OS Independent",
    ],
    python_requires='>=3.9',
)
