name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install ODBC Driver 18 for SQL Server
      run: |
        sudo su
        curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
        curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list > /etc/apt/sources.list.d/mssql-release.list
        apt-get update
        ACCEPT_EULA=Y apt-get install -y msodbcsql17
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run pytest
      env:  # Use the `env` keyword to set environment variables
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        OPENAI_ORG_ID: ${{ secrets.OPENAI_ORG_ID }}
        PROMPTLAYER_API_KEY: ${{ secrets.PROMPTLAYER_API_KEY }}
        AZURE_SQL_SERVER: ${{secrets.AZURE_SQL_SERVER}}
        AZURE_SQL_DB: ${{secrets.AZURE_SQL_DB}}
        AZURE_SQL_USER: ${{secrets.AZURE_SQL_USER}}
        AZURE_SQL_PASSWORD: ${{secrets.AZURE_SQL_PASSWORD}}
        AZURE_TABLE_NAME: ${{secrets.AZURE_TABLE_NAME}}
      run: python -m pytest
